from datetime import datetime


class Task:
    
    def __init__(self, task_id: int, description: str ="", status: str ="todo", *args, **kwargs):

        """
        Create a new Task object.
        task_id: unique identifier (generated by TaskManager)
        """

        self.id = task_id
        self.description = description
        self.status = status
        self.createdAt = f"{datetime.now():%Y-%m-%dT%H:%M:%S}"
        self.updatedAt = f"{datetime.now():%Y-%m-%dT%H:%M:%S}"
    

    @classmethod
    def from_dict(cls, data: dict):
        return cls(
            task_id=data["id"],
            description=data.get("description", ""),
            status=data.get("status", "todo"),
            created_at=data.get("createdAt"),
            updated_at=data.get("updatedAt")
        )

    def to_dict(self):
        """
        Converts the Task object to a dictionary for JSON storage.
        """
        return {
            "id": self.id,
            "description": self.description,
            "status": self.status,
            "createdAt": self.createdAt,
            "updatedAt": self.updatedAt,
        }
    
    def update(self, description=None, status=None):
        """
        Updates task properties and the updatedAt timestamp.
        """

        if description is not None:
            self.description = description

        if status is not None:
            self.status = status

        self.updatedAt = datetime.now().strftime("%Y-%m-%dT%H:%M:%S") 


    def __str__(self) -> str:
        return f"ID: {self.id}\nDescription: {self.description}\nStatus: {self.status}"